zuul_work_dir: "{{ zuul.project.src_dir }}"
zuul_work_virtualenv: "{{ ansible_user_dir }}/.venv"
sphinx_python: python2
doc_building_packages: "{{ _doc_building_packages | default([]) }}"
doc_building_extra_packages: []
