- name: Check for cached dstat_graph
  stat:
    path: "{{ dstat_graph_cache_path }}"
  register: dstat_cache

- name: Clone dstat_graph
  when: not dstat_cache.stat.exists
  git:
    repo: https://github.com/Dabz/dstat_graph
    dest: "{{ dstat_graph_download_path }}"
    version: c99e5d201ed924a816d99056f8f7d320d625b3ef
